import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type CategorySeed = {
  name: string;
  children?: Array<string | CategorySeed>;
};

const categories: CategorySeed[] = [
  {
    name: "Ambalaj ve Paketleme",
    children: [
      {
        name: "Koli ve Karton Ambalaj",
        children: [
          "Oluklu Mukavva Koliler",
          "Kargo Kolileri",
          "Ürün Kutuları",
          "Kraft Kutular",
          "Karton Levhalar",
          "Karton Köşebentler",
          "Özel Ölçü Koliler",
        ],
      },
      {
        name: "Plastik Ambalaj",
        children: [
          "Poşetler",
          "Naylon Torbalar",
          "Streç Film",
          "Shrink Film",
          "Balonlu Naylon",
          "Plastik Ambalaj Torbaları",
          "Vakum Poşetleri",
          "Plastik Kap ve Kutular",
        ],
      },
      {
        name: "Endüstriyel Ambalaj",
        children: [
          "Çemberleme Ürünleri",
          "Palet Streçleri",
          "Koruyucu Ambalaj Malzemeleri",
          "Köşe Koruyucular",
          "Ambalaj Dolgu Malzemeleri",
          "Big Bag Çuvallar",
          "Endüstriyel Çuvallar",
          "Palet Örtüleri",
        ],
      },
      {
        name: "Etiket ve Baskı",
        children: [
          "Barkod Etiketleri",
          "Termal Etiketler",
          "Kuşe Etiketler",
          "Ürün Etiketleri",
          "Kargo Etiketleri",
          "Rulo Etiketler",
          "Özel Baskılı Etiketler",
        ],
      },
      {
        name: "Koli Bandı",
        children: [
          "Şeffaf Koli Bandı",
          "Kahverengi Koli Bandı",
          "Baskılı Koli Bandı",
          "Maskeleme Bantları",
          "Çift Taraflı Bantlar",
          "Endüstriyel Bantlar",
          "Bant Kesme Makineleri",
        ],
      },
    ],
  },
  {
    name: "Temizlik ve Hijyen",
    children: [
      {
        name: "Endüstriyel Temizlik",
        children: [
          "Genel Temizlik Ürünleri",
          "Yüzey Temizleyiciler",
          "Yağ Çözücüler",
          "Zemin Temizleyiciler",
          "Bulaşık Deterjanları",
          "Çamaşır Deterjanları",
          "Dezenfektanlar",
          "Endüstriyel Temizlik Kimyasalları",
        ],
      },
      {
        name: "Kağıt Ürünleri",
        children: [
          "Tuvalet Kağıdı",
          "Kağıt Havlu",
          "Z Katlama Havlu",
          "İçten Çekmeli Havlu",
          "Peçeteler",
          "Dispenser Peçeteler",
          "Muayene Masa Örtüleri",
        ],
      },
      {
        name: "Temizlik Ekipmanları",
        children: [
          "Mop ve Paspaslar",
          "Temizlik Arabaları",
          "Fırça ve Süpürgeler",
          "Kovalar",
          "Cam Temizlik Ekipmanları",
          "Çöp Kovaları",
          "Temizlik Makineleri",
          "Temizlik Bezi ve Süngerleri",
        ],
      },
      {
        name: "Hijyen Sarf Malzemeleri",
        children: [
          "Islak Mendiller",
          "Sıvı Sabunlar",
          "El Dezenfektanları",
          "Tek Kullanımlık Eldivenler",
          "Çöp Torbaları",
          "Hijyen Poşetleri",
          "Kağıt Dispenserleri",
          "Sabun ve Dezenfektan Dispenserleri",
        ],
      },
    ],
  },
  {
    name: "Hırdavat",
    children: [
      {
        name: "Vida ve Bağlantı Elemanları",
        children: [
          "Vidalar",
          "Cıvatalar",
          "Somunlar",
          "Pullar",
          "Dübeller",
          "Ankrajlar",
          "Perçinler",
          "Saplama ve Tijler",
          "Kelepçeler",
          "Mobilya Bağlantı Elemanları",
        ],
      },
      {
        name: "El Aletleri",
        children: [
          "Tornavidalar",
          "Pense ve Kargaburunlar",
          "Anahtar Takımları",
          "Lokma Takımları",
          "Çekiç ve Tokmaklar",
          "Keski ve Murçlar",
          "Eğe ve Törpüler",
          "Maket Bıçakları",
          "Mengene ve İşkenceler",
          "Ölçüm El Aletleri",
          "Takım Çantaları",
        ],
      },
      {
        name: "Elektrikli El Aletleri",
        children: [
          "Matkaplar",
          "Vidalama Makineleri",
          "Taşlama Makineleri",
          "Daire Testereler",
          "Dekupaj Testereler",
          "Kırıcı ve Deliciler",
          "Zımpara Makineleri",
          "Freze ve Planya Makineleri",
          "Polisaj Makineleri",
          "Sıcak Hava Tabancaları",
          "Akülü El Aletleri",
          "Elektrikli El Aleti Aksesuarları",
        ],
      },
      {
        name: "Kesici ve Delici Aletler",
        children: [
          "Matkap Uçları",
          "Testere Bıçakları",
          "Kesme Diskleri",
          "Taşlama Diskleri",
          "Delik Testereleri",
          "Kılavuz ve Paftalar",
          "Freze Uçları",
          "Karot Uçları",
          "Kesici Bıçaklar",
        ],
      },
      {
        name: "Yapıştırıcı ve Kimyasallar",
        children: [
          "Silikonlar",
          "Montaj Yapıştırıcıları",
          "Epoksi Yapıştırıcılar",
          "Hızlı Yapıştırıcılar",
          "Vida Sabitleyiciler",
          "Mastikler",
          "Poliüretan Köpükler",
          "Pas Sökücüler",
          "Teknik Spreyler",
          "Yüzey Temizleyiciler",
        ],
      },
      {
        name: "İş Güvenliği",
        children: [
          "İş Eldivenleri",
          "Koruyucu Gözlükler",
          "Baretler",
          "İş Ayakkabıları",
          "İş Kıyafetleri",
          "Kulak Koruyucular",
          "Solunum Koruyucuları",
          "Emniyet Kemerleri",
          "İkaz ve Güvenlik Ürünleri",
        ],
      },
    ],
  },
  {
    name: "Elektrik ve Aydınlatma",
    children: [
      {
        name: "Elektrik Malzemeleri",
        children: [
          "Priz ve Anahtarlar",
          "Sigorta ve Şalterler",
          "Kaçak Akım Röleleri",
          "Kontaktör ve Röleler",
          "Elektrik Panoları",
          "Klemensler",
          "Fiş ve Soketler",
          "Sensörler",
          "Zaman Röleleri",
          "Elektrik Sayaçları",
          "Topraklama Malzemeleri",
          "Elektrik Sarf Malzemeleri",
        ],
      },
      {
        name: "Aydınlatma",
        children: [
          "LED Ampuller",
          "LED Paneller",
          "Projektörler",
          "Endüstriyel Aydınlatma",
          "Ofis Aydınlatma",
          "Dış Mekan Aydınlatma",
          "Acil Aydınlatma",
          "Şerit LED ve Aksesuarları",
          "Armatürler",
          "Sensörlü Aydınlatma",
        ],
      },
      {
        name: "Endüstriyel Elektrik",
        children: [
          "Motor Koruma Ürünleri",
          "Kumanda Elemanları",
          "Endüstriyel Priz ve Fişler",
          "Frekans İnverterleri",
          "Soft Starter",
          "Güç Kaynakları",
          "Trafo ve Transformatörler",
          "Kompanzasyon Ürünleri",
          "Otomasyon Ürünleri",
          "Pano Ekipmanları",
        ],
      },
      {
        name: "Kablo ve Kablo Kanalları",
        children: [
          "Enerji Kabloları",
          "Tesisat Kabloları",
          "Data Kabloları",
          "Koaksiyel Kablolar",
          "Yangına Dayanıklı Kablolar",
          "Kablo Kanalları",
          "Kablo Tavaları",
          "Kablo Rakorları",
          "Kablo Bağları",
          "Kablo Pabuçları",
          "Kablo Ek ve Bağlantı Ürünleri",
        ],
      },
    ],
  },
  {
    name: "Gıda ve Horeca",
    children: [
      {
        name: "Gıda Hammaddeleri",
        children: [
          "Un ve Tahıl Ürünleri",
          "Şeker ve Tatlandırıcılar",
          "Nişasta ve Kıvam Vericiler",
          "Baharatlar ve Çeşniler",
          "Bitkisel Yağlar",
          "Kakao ve Çikolata Hammaddeleri",
          "Süt ve Süt Ürünleri Hammaddeleri",
          "Pastacılık Hammaddeleri",
          "Kuruyemiş ve Kuru Meyveler",
          "Gıda Katkı Maddeleri",
          "Aroma ve Esanslar",
          "Dondurulmuş Gıda Hammaddeleri",
        ],
      },
      {
        name: "Kahve ve İçecek",
        children: [
          "Çekirdek Kahve",
          "Öğütülmüş Kahve",
          "Türk Kahvesi",
          "Filtre Kahve",
          "Hazır Kahve",
          "Çay",
          "Bitki Çayları",
          "Sıcak Çikolata",
          "Meyve Suları",
          "Konsantre İçecekler",
          "Şurup ve Soslar",
          "Su ve Maden Suyu",
        ],
      },
      {
        name: "Horeca Tedarik",
        children: [
          "Endüstriyel Mutfak Ekipmanları",
          "Pişirme Ekipmanları",
          "Hazırlık Ekipmanları",
          "Servis Ekipmanları",
          "Tabak ve Sunum Ürünleri",
          "Bardak ve Kadehler",
          "Çatal Kaşık Bıçak",
          "Gastronom Küvetler",
          "Mutfak Gereçleri",
          "Bar Ekipmanları",
          "Otel Sarf Malzemeleri",
          "Restoran Sarf Malzemeleri",
        ],
      },
      {
        name: "Tek Kullanımlık Ürünler",
        children: [
          "Karton Bardaklar",
          "Plastik Bardaklar",
          "Kağıt Tabaklar",
          "Tek Kullanımlık Tabaklar",
          "Tek Kullanımlık Çatal Kaşık",
          "Pipetler",
          "Paket Servis Kapları",
          "Alüminyum Kaplar",
          "Kraft Gıda Kapları",
          "Peçeteler",
          "Islak Mendiller",
          "Tek Kullanımlık Eldivenler",
        ],
      },
    ],
  },
  {
    name: "Otomotiv ve Yedek Parça",
    children: [
      {
        name: "Motor Parçaları",
        children: [
          "Filtreler",
          "Triger ve Kayış Sistemleri",
          "Motor Contaları",
          "Piston ve Segmanlar",
          "Supap ve Eksantrik Parçaları",
          "Turbo Parçaları",
          "Yakıt Sistemi Parçaları",
          "Soğutma Sistemi Parçaları",
          "Debriyaj Parçaları",
          "Motor Takozları",
        ],
      },
      {
        name: "Bakım Ürünleri",
        children: [
          "Motor Yağları",
          "Şanzıman Yağları",
          "Antifriz ve Soğutma Sıvıları",
          "Fren Hidrolikleri",
          "Araç Temizlik Ürünleri",
          "Oto Bakım Kimyasalları",
          "Cam Suları",
          "Gresler",
          "Katkı Ürünleri",
          "Filtre Bakım Ürünleri",
        ],
      },
      {
        name: "Fren Sistemleri",
        children: [
          "Fren Balataları",
          "Fren Diskleri",
          "Fren Kampanaları",
          "Fren Hidrolik Parçaları",
          "Fren Hortumları",
          "ABS Sensörleri",
          "El Freni Parçaları",
          "Fren Merkezi ve Kaliperler",
        ],
      },
      {
        name: "Elektrik Parçaları",
        children: [
          "Aküler",
          "Alternatörler",
          "Marş Motorları",
          "Far ve Aydınlatma",
          "Sensörler",
          "Ateşleme Bobinleri",
          "Bujiler",
          "Sigorta ve Röleler",
          "Oto Kabloları",
          "Elektronik Kontrol Parçaları",
        ],
      },
    ],
  },

  {
    name: "Dental ve Diş Hekimliği",
    children: [
      {
        name: "Dental Sarf Malzemeleri",
        children: [
          "Dental Eldivenler",
          "Dental Maskeler",
          "Hasta Önlükleri",
          "Tükürük Emiciler",
          "Pamuk Rulolar",
          "Mikro Fırçalar",
          "Karıştırma Uçları",
          "Aplikatörler",
          "Dental İğneler",
          "Tek Kullanımlık Dental Ürünler",
        ],
      },
      {
        name: "Endodonti",
        children: [
          "Kanal Eğeleri",
          "Gutta Percha",
          "Paper Point",
          "Kanal Dolgu Patları",
          "Apeks Bulucular",
          "Endodontik Motorlar",
          "Kanal İrrigasyon Ürünleri",
          "Endodontik Aksesuarlar",
        ],
      },
      {
        name: "Restoratif Diş Hekimliği",
        children: [
          "Kompozitler",
          "Bonding Sistemleri",
          "Asitler",
          "Cam İyonomerler",
          "Matris Sistemleri",
          "Kama ve Separatörler",
          "Polisaj Ürünleri",
          "Geçici Dolgu Malzemeleri",
        ],
      },
      {
        name: "Protez ve Dental Laboratuvar",
        children: [
          "Ölçü Malzemeleri",
          "Aljinatlar",
          "Silikon Ölçü Malzemeleri",
          "Dental Alçılar",
          "Akrilikler",
          "Laboratuvar Frezleri",
          "Modelaj Malzemeleri",
          "Protez Laboratuvar Ekipmanları",
        ],
      },
      {
        name: "Ortodonti",
        children: [
          "Braketler",
          "Ortodontik Teller",
          "Bantlar ve Tüpler",
          "Elastikler",
          "Ortodontik Pensler",
          "Retainer Ürünleri",
          "Ortodontik Aksesuarlar",
        ],
      },
      {
        name: "Cerrahi ve İmplantoloji",
        children: [
          "Dental İmplantlar",
          "İmplant Üstü Parçalar",
          "Cerrahi Frezler",
          "Sütur Malzemeleri",
          "Cerrahi Aspirasyon Ürünleri",
          "Kemik Greftleri",
          "Membranlar",
          "Cerrahi Setler",
        ],
      },
      {
        name: "Dental El Aletleri",
        children: [
          "Ayna ve Sondlar",
          "Ekskavatörler",
          "Elevatörler",
          "Davye ve Pensler",
          "Küretler",
          "Periodontal Aletler",
          "Spatüller",
          "Dental El Aleti Setleri",
        ],
      },
      {
        name: "Dental Cihaz ve Ekipman",
        children: [
          "Dental Ünitler",
          "Mikromotorlar",
          "Aeratorlar",
          "Anguldruvalar",
          "Kavitronlar",
          "Işınlı Dolgu Cihazları",
          "Dental Röntgen Sistemleri",
          "Ağız İçi Kameralar",
          "Dental Kompresörler",
          "Dental Aspirasyon Sistemleri",
        ],
      },
      {
        name: "Dezenfeksiyon ve Sterilizasyon",
        children: [
          "Dental Otoklavlar",
          "Sterilizasyon Poşetleri",
          "Sterilizasyon Ruloları",
          "Dezenfektanlar",
          "Ultrasonik Temizleme Cihazları",
          "İndikatörler",
          "Alet Temizleme Ürünleri",
        ],
      },
      {
        name: "Diş Hekimliği Öğrenci Malzemeleri",
        children: [
          "Fantoma Malzemeleri",
          "Öğrenci El Aleti Setleri",
          "Diş Modelleri",
          "Pratik Dişler",
          "Öğrenci Frez Setleri",
          "Laboratuvar Önlükleri",
          "Eğitim Sarf Malzemeleri",
        ],
      },
    ],
  },

  {
    name: "Medikal ve Sağlık",
    children: [
      {
        name: "Medikal Sarf Malzemeleri",
        children: [
          "Enjektör ve İğneler",
          "Eldivenler",
          "Maskeler",
          "Gazlı Bez ve Kompresler",
          "Bandaj ve Sargılar",
          "Flasterler",
          "Kateterler",
          "Kan Alma Ürünleri",
          "Serum ve İnfüzyon Setleri",
          "Numune Kapları",
          "Tek Kullanımlık Önlükler",
          "Medikal Tek Kullanımlık Ürünler",
        ],
      },
      {
        name: "Muayene ve Klinik Ekipmanları",
        children: [
          "Stetoskoplar",
          "Tansiyon Aletleri",
          "Termometreler",
          "Pulse Oksimetreler",
          "EKG Cihazları",
          "Muayene Masaları",
          "Muayene Lambaları",
          "Hasta Monitörleri",
          "Nebulizatörler",
          "Aspiratörler",
          "Tıbbi Tartılar",
          "Tanı ve Ölçüm Cihazları",
        ],
      },
      {
        name: "Hasta Bakım Ürünleri",
        children: [
          "Hasta Yatakları",
          "Tekerlekli Sandalyeler",
          "Yürüteç ve Walker",
          "Koltuk Değnekleri",
          "Hasta Altı Bezleri",
          "Yetişkin Hasta Bezleri",
          "Yara Bakım Ürünleri",
          "Ortopedik Destek Ürünleri",
          "Hasta Transfer Ürünleri",
          "Evde Bakım Ekipmanları",
        ],
      },
      {
        name: "Sterilizasyon Ürünleri",
        children: [
          "Sterilizasyon Poşetleri",
          "Sterilizasyon Ruloları",
          "Sterilizasyon İndikatörleri",
          "Otoklavlar",
          "Ultrasonik Temizleyiciler",
          "Yüzey Dezenfektanları",
          "El Dezenfektanları",
          "Alet Dezenfektanları",
          "Sterilizasyon Konteynerleri",
          "Sterilizasyon Sarf Malzemeleri",
        ],
      },
    ],
  },

  {
    name: "Tekstil ve Konfeksiyon",
    children: [
      {
        name: "Kumaş",
        children: [
          "Pamuklu Kumaşlar",
          "Örme Kumaşlar",
          "Dokuma Kumaşlar",
          "Denim Kumaşlar",
          "Polyester Kumaşlar",
          "Viskon Kumaşlar",
          "Keten Kumaşlar",
          "Şifon ve Saten Kumaşlar",
          "Döşemelik Kumaşlar",
          "Astar Kumaşları",
          "Teknik Tekstiller",
          "Nonwoven Kumaşlar",
        ],
      },
      {
        name: "İplik",
        children: [
          "Pamuk İpliği",
          "Polyester İplik",
          "Viskon İplik",
          "Naylon İplik",
          "Dikiş İpliği",
          "Örgü İpliği",
          "Elastan İplik",
          "Teknik İplikler",
        ],
      },
      {
        name: "Düğme ve Aksesuar",
        children: [
          "Düğmeler",
          "Çıtçıtlar",
          "Kopçalar",
          "Tokalar",
          "Lastikler",
          "Şerit ve Biye",
          "Dantel ve Güpür",
          "Etiketler",
          "Kordonlar",
          "Tekstil Aksesuarları",
        ],
      },
      {
        name: "Fermuar",
        children: [
          "Kemik Fermuar",
          "Metal Fermuar",
          "Spiral Fermuar",
          "Gizli Fermuar",
          "Mont Fermuarı",
          "Çanta Fermuarı",
          "Fermuar Elcikleri",
          "Metraj Fermuar",
        ],
      },
      {
        name: "Fason Dikim",
        children: [
          "Kadın Giyim Fason Üretim",
          "Erkek Giyim Fason Üretim",
          "Çocuk Giyim Fason Üretim",
          "İç Giyim Fason Üretim",
          "Spor Giyim Fason Üretim",
          "İş Elbisesi Fason Üretim",
          "Ev Tekstili Fason Üretim",
          "Numune Dikim Hizmetleri",
        ],
      },
      {
        name: "Konfeksiyon Sarf Malzemeleri",
        children: [
          "Tela",
          "Astar",
          "Omuz Vatkaları",
          "Tekstil Etiketleri",
          "Askılar",
          "Poşet ve Ambalaj",
          "Kesim Sarf Malzemeleri",
          "Dikim Sarf Malzemeleri",
          "Ütü ve Pres Sarfları",
        ],
      },
      {
        name: "Kadın Giyim",
        children: [
          "Elbise",
          "Bluz",
          "Gömlek",
          "T-Shirt",
          "Sweatshirt",
          "Triko ve Kazak",
          "Pantolon",
          "Etek",
          "Tayt",
          "Ceket",
          "Mont ve Kaban",
          "Trençkot",
          "Spor Giyim",
          "Büyük Beden",
          "Tesettür Giyim",
        ],
      },
      {
        name: "Erkek Giyim",
        children: [
          "T-Shirt",
          "Polo T-Shirt",
          "Gömlek",
          "Sweatshirt",
          "Triko ve Kazak",
          "Pantolon",
          "Şort",
          "Eşofman",
          "Ceket",
          "Takım Elbise",
          "Mont ve Kaban",
          "Yağmurluk",
          "Spor Giyim",
          "İş Giyimi",
        ],
      },
      {
        name: "İç Giyim ve Ev Giyim",
        children: [
          "Kadın İç Giyim",
          "Erkek İç Giyim",
          "Çorap",
          "Pijama",
          "Gecelik",
          "Ev Giyim",
          "Termal Giyim",
          "Plaj Giyim",
        ],
      },
      {
        name: "Ayakkabı ve Çanta",
        children: [
          "Kadın Günlük Ayakkabı",
          "Kadın Spor Ayakkabı",
          "Kadın Bot ve Çizme",
          "Kadın Sandalet ve Terlik",
          "Erkek Günlük Ayakkabı",
          "Erkek Spor Ayakkabı",
          "Erkek Klasik Ayakkabı",
          "Erkek Bot",
          "Outdoor Ayakkabı",
          "Kadın Çanta",
          "Erkek Çanta",
          "Sırt Çantası",
          "Valiz ve Seyahat Çantası",
        ],
      },
      {
        name: "Moda Aksesuarları",
        children: [
          "Kemer",
          "Şapka ve Bere",
          "Atkı ve Şal",
          "Eldiven",
          "Cüzdan",
          "Takı ve Bijuteri",
          "Güneş Gözlüğü",
          "Saat Aksesuarları",
        ],
      },
      {
        name: "Çocuk ve Bebek Giyim",
        children: [
          "Kız Çocuk Giyim",
          "Erkek Çocuk Giyim",
          "Bebek Giyim",
          "Bebek Body ve Zıbın",
          "Çocuk T-Shirt",
          "Çocuk Sweatshirt",
          "Çocuk Pantolon",
          "Çocuk Elbise",
          "Çocuk Eşofman",
          "Çocuk Mont ve Kaban",
          "Okul Giyimi",
          "Çocuk İç Giyim",
          "Çocuk Çorap",
        ],
      },
      {
        name: "Ev Tekstili",
        children: [
          "Nevresim Takımları",
          "Çarşaf ve Yastık Kılıfları",
          "Yorgan ve Battaniye",
          "Havlu ve Bornoz",
          "Mutfak Tekstili",
          "Masa Örtüsü",
          "Perde ve Tül",
          "Koltuk Örtüsü",
          "Dekoratif Yastık ve Kırlent",
          "Otel Tekstili",
          "Hastane Tekstili",
          "Toplu Ev Tekstili Ürünleri",
        ],
      },
    ],
  },

  {
    name: "Eğitim ve Okul Malzemeleri",
    children: [
      {
        name: "Okul Kırtasiyesi",
        children: [
          "Kurşun Kalemler",
          "Tükenmez Kalemler",
          "Silgi ve Kalemtıraşlar",
          "Defterler",
          "Dosya ve Klasörler",
          "Cetvel ve Geometri Setleri",
          "Kalem Kutuları",
          "Yapıştırıcılar",
          "Makaslar",
          "Okul Boyaları",
          "Okul Çantaları",
          "Beslenme Ürünleri",
        ],
      },
      {
        name: "Üniversite Malzemeleri",
        children: [
          "Spiralli Defterler",
          "Ajanda ve Planlayıcılar",
          "Teknik Çizim Malzemeleri",
          "Mimarlık Malzemeleri",
          "Mühendislik Çizim Gereçleri",
          "Hesap Makineleri",
          "Sunum Malzemeleri",
          "Proje Dosyaları",
          "Not Alma Ürünleri",
        ],
      },
      {
        name: "Sanat ve Çizim Malzemeleri",
        children: [
          "Resim Kağıtları",
          "Tuval",
          "Akrilik Boyalar",
          "Yağlı Boyalar",
          "Sulu Boyalar",
          "Guaj Boyalar",
          "Pastel Boyalar",
          "Fırçalar",
          "Eskiz Ürünleri",
          "Marker Kalemler",
          "Hobi Malzemeleri",
          "Seramik ve Heykel Malzemeleri",
        ],
      },
      {
        name: "Laboratuvar Eğitim Setleri",
        children: [
          "Fen Deney Setleri",
          "Kimya Deney Setleri",
          "Fizik Deney Setleri",
          "Biyoloji Eğitim Setleri",
          "Mikroskop Eğitim Setleri",
          "Elektronik Eğitim Setleri",
          "Robotik Kodlama Setleri",
          "STEM Eğitim Setleri",
          "Laboratuvar Eğitim Sarfları",
        ],
      },
      {
        name: "Toplu Okul İhtiyaçları",
        children: [
          "Sınıf Yazı Tahtaları",
          "Okul Sıraları",
          "Öğrenci Sandalyeleri",
          "Öğretmen Masaları",
          "Sınıf Dolapları",
          "Pano ve Eğitim Panoları",
          "Toplu Kırtasiye Paketleri",
          "Okul Temizlik Sarfları",
          "Okul Etkinlik Malzemeleri",
        ],
      },
    ],
  },

  {
    name: "Kozmetik ve Kuaför",
    children: [
      {
        name: "Kuaför Sarf Malzemeleri",
        children: [
          "Kuaför Havluları",
          "Tek Kullanımlık Havlular",
          "Boyun Bantları",
          "Saç Boyama Fırçaları",
          "Boya Kapları",
          "Folyolar",
          "Saç Bonesi",
          "Kuaför Önlükleri",
          "Eldivenler",
          "Tarak ve Fırçalar",
          "Saç Klipsleri",
          "Dezenfeksiyon Ürünleri",
        ],
      },
      {
        name: "Profesyonel Saç Ürünleri",
        children: [
          "Şampuanlar",
          "Saç Kremleri",
          "Saç Maskeleri",
          "Saç Boyaları",
          "Oksidanlar",
          "Saç Açıcılar",
          "Keratin Bakım Ürünleri",
          "Saç Serumları",
          "Saç Spreyleri",
          "Jöle ve Wax",
          "Saç Şekillendiriciler",
          "Profesyonel Saç Bakım Setleri",
        ],
      },
      {
        name: "Cilt Bakım Ürünleri",
        children: [
          "Yüz Temizleme Ürünleri",
          "Nemlendiriciler",
          "Serumlar",
          "Maskeler",
          "Peeling Ürünleri",
          "Tonikler",
          "Güneş Bakım Ürünleri",
          "El ve Vücut Bakımı",
          "Profesyonel Cilt Bakım Ürünleri",
          "Spa ve Masaj Ürünleri",
          "Ağda ve Epilasyon Ürünleri",
        ],
      },
      {
        name: "Salon Ekipmanları",
        children: [
          "Kuaför Koltukları",
          "Yıkama Setleri",
          "Kuaför Tezgahları",
          "Manikür Masaları",
          "Bakım Yatakları",
          "Saç Kurutma Makineleri",
          "Fön Makineleri",
          "Saç Düzleştiriciler",
          "Saç Maşaları",
          "Tıraş Makineleri",
          "Sterilizasyon Cihazları",
          "Salon Arabaları",
        ],
      },
    ],
  },

  {
    name: "Laboratuvar",
    children: [
      {
        name: "Laboratuvar Sarf Malzemeleri",
        children: [
          "Pipet Uçları",
          "Santrifüj Tüpleri",
          "Numune Kapları",
          "Petri Kapları",
          "Mikroskop Lamları",
          "Lameller",
          "Filtre Kağıtları",
          "Laboratuvar Eldivenleri",
          "Laboratuvar Etiketleri",
          "Tek Kullanımlık Laboratuvar Ürünleri",
        ],
      },
      {
        name: "Cam Malzemeler",
        children: [
          "Beherler",
          "Erlenler",
          "Mezürler",
          "Balon Jojeler",
          "Deney Tüpleri",
          "Cam Pipetler",
          "Büretler",
          "Ayırma Hunileri",
          "Reaktif Şişeleri",
          "Laboratuvar Cam Setleri",
        ],
      },
      {
        name: "Ölçüm ve Test Cihazları",
        children: [
          "pH Metreler",
          "İletkenlik Ölçerler",
          "Refraktometreler",
          "Spektrofotometreler",
          "Hassas Teraziler",
          "Nem Ölçerler",
          "Sıcaklık Ölçerler",
          "Su Analiz Cihazları",
          "Test Kitleri",
          "Veri Kaydediciler",
        ],
      },
      {
        name: "Laboratuvar Ekipmanları",
        children: [
          "Mikroskoplar",
          "Santrifüjler",
          "Etüvler",
          "İnkübatörler",
          "Manyetik Karıştırıcılar",
          "Isıtıcı Tablalar",
          "Su Banyoları",
          "Çeker Ocaklar",
          "Otoklavlar",
          "Laboratuvar Buzdolapları",
        ],
      },
    ],
  },

  {
    name: "Veteriner ve Pet Ürünleri",
    children: [
      {
        name: "Veteriner Sarf Malzemeleri",
        children: [
          "Veteriner Enjektörleri",
          "Veteriner İğneleri",
          "Muayene Eldivenleri",
          "Bandaj ve Sargılar",
          "Yara Bakım Ürünleri",
          "Numune Alma Ürünleri",
          "Cerrahi Sarf Malzemeleri",
          "Veteriner Tek Kullanımlık Ürünler",
        ],
      },
      {
        name: "Klinik Ekipmanları",
        children: [
          "Veteriner Muayene Masaları",
          "Veteriner Tartıları",
          "Stetoskoplar",
          "Ultrason Cihazları",
          "Hasta Monitörleri",
          "Veteriner Kafesleri",
          "Cerrahi Ekipmanlar",
          "Tıraş Makineleri",
          "Sterilizasyon Ekipmanları",
        ],
      },
      {
        name: "Pet Bakım Ürünleri",
        children: [
          "Pet Şampuanları",
          "Tüy Bakım Ürünleri",
          "Tarama ve Fırçalama Ürünleri",
          "Pet Hijyen Ürünleri",
          "Kedi Kumları",
          "Tuvalet ve Kum Kapları",
          "Pet Pedleri",
          "Mama ve Su Kapları",
          "Taşıma Çantaları",
          "Pet Aksesuarları",
        ],
      },
      {
        name: "Mama ve Beslenme",
        children: [
          "Kedi Mamaları",
          "Köpek Mamaları",
          "Yaş Mamalar",
          "Kuru Mamalar",
          "Yavru Hayvan Mamaları",
          "Ödül Mamaları",
          "Pet Besin Takviyeleri",
          "Kuş Yemleri",
          "Balık Yemleri",
          "Toplu Mama Ürünleri",
        ],
      },
    ],
  },

  {
    name: "Fason Üretim ve Özel Üretim",
    children: [
      {
        name: "Fason Tekstil Üretimi",
        children: [
          "Fason Kesim",
          "Fason Dikim",
          "Fason Baskı ve Nakış",
          "Fason Örme",
          "Fason Dokuma",
          "Tekstil Paketleme",
        ],
      },
      {
        name: "Fason Kozmetik Üretimi",
        children: [
          "Cilt Bakım Üretimi",
          "Saç Bakım Üretimi",
          "Kişisel Bakım Üretimi",
          "Parfüm Üretimi",
          "Sabun Üretimi",
          "Kozmetik Dolum ve Paketleme",
        ],
      },
      {
        name: "Fason Gıda Üretimi",
        children: [
          "Atıştırmalık Üretimi",
          "İçecek Üretimi",
          "Kahve ve Çay Paketleme",
          "Baharat Paketleme",
          "Sos ve Şurup Üretimi",
          "Gıda Dolum ve Paketleme",
        ],
      },
      {
        name: "Özel Ambalaj Üretimi",
        children: [
          "Özel Kutu Üretimi",
          "Özel Poşet Üretimi",
          "Baskılı Ambalaj Üretimi",
          "Etiket Üretimi",
          "Karton Ambalaj Üretimi",
          "Plastik Ambalaj Üretimi",
        ],
      },
      {
        name: "Markaya Özel Üretim",
        children: [
          "Private Label Üretim",
          "OEM Üretim",
          "ODM Üretim",
          "Numune ve Prototip Üretimi",
          "Özel Formülasyon Üretimi",
          "Markalı Paketleme",
        ],
      },
    ],
  },

  {
    name: "Diğer Ürün ve Hizmetler",
    children: [
      "Diğer Ürünler",
      "Diğer Sarf Malzemeleri",
      "Diğer Ekipmanlar",
      "Diğer Hizmetler",
      "Kategorisi Belirlenemeyen Ürünler",
    ],
  },

  {
    name: "İnşaat ve Yapı Malzemeleri",
    children: [
      {
        name: "Çimento ve Harç",
        children: [
          "Çimento",
          "Hazır Harç",
          "Tamir Harçları",
          "Sıva Harçları",
          "Şap Malzemeleri",
          "Derz Dolguları",
          "Gazbeton Yapıştırıcıları",
          "Tuğla ve Blok Yapıştırıcıları",
        ],
      },
      {
        name: "Boya ve Kaplama",
        children: [
          "İç Cephe Boyaları",
          "Dış Cephe Boyaları",
          "Metal Boyaları",
          "Ahşap Boyaları",
          "Astarlar",
          "Vernikler",
          "Sprey Boyalar",
          "Zemin Kaplamaları",
          "Boya Ruloları ve Fırçaları",
          "Boya Sarf Malzemeleri",
        ],
      },
      {
        name: "Yapı Kimyasalları",
        children: [
          "Seramik Yapıştırıcıları",
          "Su Yalıtım Ürünleri",
          "Beton Katkıları",
          "Epoksi Ürünleri",
          "Mastikler",
          "Silikonlar",
          "Poliüretan Köpükler",
          "Ankraj Kimyasalları",
          "Yüzey Sertleştiriciler",
          "Tamir ve Güçlendirme Ürünleri",
        ],
      },
      {
        name: "İzolasyon Malzemeleri",
        children: [
          "Isı Yalıtım Levhaları",
          "Taş Yünü",
          "Cam Yünü",
          "XPS Levhalar",
          "EPS Levhalar",
          "Su Yalıtım Membranları",
          "Çatı Yalıtım Ürünleri",
          "Ses Yalıtım Malzemeleri",
          "Buhar Kesici Ürünler",
        ],
      },
      {
        name: "İnşaat Sarf Malzemeleri",
        children: [
          "İnşaat Teli",
          "Çivi ve Bağlantı Ürünleri",
          "Kalıp Malzemeleri",
          "İnşaat Filesi",
          "Derz Artıları ve Takozları",
          "Mala ve Spatulalar",
          "Ölçüm ve İşaretleme Ürünleri",
          "Koruyucu Örtüler",
          "İnşaat Kovaları",
          "Şantiye Sarf Malzemeleri",
        ],
      },
    ],
  },
  {
    name: "Metal ve Çelik",
    children: [
      {
        name: "Sac",
        children: [
          "Siyah Sac",
          "Galvaniz Sac",
          "DKP Sac",
          "HRP Sac",
          "Boyalı Sac",
          "Baklavalı Sac",
          "Delikli Sac",
          "Rulo Sac",
          "Alüminyum Sac",
        ],
      },
      {
        name: "Profil",
        children: [
          "Kutu Profil",
          "Dikdörtgen Profil",
          "Kare Profil",
          "U Profil",
          "C Profil",
          "L Profil",
          "I Profil",
          "HEA HEB Profil",
          "Alüminyum Profil",
          "Paslanmaz Profil",
        ],
      },
      {
        name: "Boru",
        children: [
          "Çelik Boru",
          "Sanayi Borusu",
          "Galvaniz Boru",
          "Paslanmaz Boru",
          "Dikişli Boru",
          "Dikişsiz Boru",
          "Kazan Borusu",
          "Profil Boru",
          "Alüminyum Boru",
        ],
      },
      {
        name: "Paslanmaz Çelik",
        children: [
          "Paslanmaz Sac",
          "Paslanmaz Rulo",
          "Paslanmaz Boru",
          "Paslanmaz Profil",
          "Paslanmaz Çubuk",
          "Paslanmaz Lama",
          "Paslanmaz Köşebent",
          "Paslanmaz Tel",
          "Paslanmaz Bağlantı Elemanları",
        ],
      },
      {
        name: "Metal İşleme Ürünleri",
        children: [
          "Çelik Çubuklar",
          "Lama Demir",
          "Köşebent",
          "NPI ve NPU Profiller",
          "Metal Hasır",
          "Metal Teller",
          "Metal Izgaralar",
          "Kesilmiş Metal Parçalar",
          "Lazer Kesim Ürünleri",
          "CNC İşlenmiş Metal Parçalar",
        ],
      },
    ],
  },
  {
    name: "Mobilya ve Ofis",
    children: [
      {
        name: "Ofis Masaları",
        children: [
          "Çalışma Masaları",
          "Yönetici Masaları",
          "Personel Masaları",
          "Bilgisayar Masaları",
          "Ortak Çalışma Masaları",
          "Resepsiyon Bankoları",
          "Masa Modülleri",
        ],
      },
      {
        name: "Ofis Sandalyeleri",
        children: [
          "Çalışma Koltukları",
          "Yönetici Koltukları",
          "Misafir Koltukları",
          "Toplantı Sandalyeleri",
          "Bekleme Koltukları",
          "Ergonomik Ofis Koltukları",
          "Tabureler",
        ],
      },
      {
        name: "Dolap ve Arşiv Sistemleri",
        children: [
          "Dosya Dolapları",
          "Metal Dolaplar",
          "Ahşap Ofis Dolapları",
          "Arşiv Dolapları",
          "Kesonlar",
          "Kitaplıklar",
          "Raf Sistemleri",
          "Soyunma Dolapları",
        ],
      },
      {
        name: "Toplantı Mobilyaları",
        children: [
          "Toplantı Masaları",
          "Konferans Masaları",
          "Toplantı Sandalyeleri",
          "Seminer Sandalyeleri",
          "Konferans Koltukları",
          "Eğitim Masaları",
        ],
      },
      {
        name: "Ofis Aksesuarları",
        children: [
          "Masaüstü Düzenleyiciler",
          "Monitör Standları",
          "Ayak Destekleri",
          "Ergonomi Ürünleri",
          "Askılıklar",
          "Çöp Kovaları",
          "Pano ve Yazı Tahtaları",
          "Ofis Bölme Sistemleri",
        ],
      },
      {
        name: "Ev ve Yaşam Mobilyaları",
        children: [
          "Koltuk ve Oturma Grupları",
          "Yatak Odası Mobilyaları",
          "Yemek Odası Mobilyaları",
          "TV Üniteleri",
          "Sehpa ve Yan Masalar",
          "Kitaplık ve Raflar",
          "Antre Mobilyaları",
          "Genç Odası Mobilyaları",
          "Bahçe ve Balkon Mobilyaları",
        ],
      },
      {
        name: "Mutfak ve Sofra",
        children: [
          "Tencere ve Tavalar",
          "Çaydanlıklar",
          "Kahve Demleme Ürünleri",
          "Yemek Takımları",
          "Kahvaltı Takımları",
          "Çatal Kaşık Bıçak Takımları",
          "Bardak ve Kupalar",
          "Mutfak Gereçleri",
          "Saklama Kapları",
          "Mutfak Düzenleme Ürünleri",
        ],
      },
      {
        name: "Ev Tekstili",
        children: [
          "Nevresim Takımları",
          "Çarşaflar",
          "Yorganlar",
          "Yastıklar",
          "Battaniyeler",
          "Havlular",
          "Banyo Tekstili",
          "Mutfak Tekstili",
          "Perdeler",
          "Halı ve Kilimler",
        ],
      },
      {
        name: "Ev Dekorasyon",
        children: [
          "Dekoratif Aksesuarlar",
          "Aynalar",
          "Tablolar",
          "Duvar Dekorasyonu",
          "Dekoratif Saksılar",
          "Mum ve Kokular",
          "Dekoratif Kutular",
          "Masaüstü Dekorasyon",
        ],
      },
      {
        name: "Elektrikli Ev Aletleri",
        children: [
          "Elektrikli Mutfak Aletleri",
          "Kahve Makineleri",
          "Çay Makineleri",
          "Tost Makineleri",
          "Blender ve Mikserler",
          "Su Isıtıcıları",
          "Ütüler",
          "Elektrikli Süpürgeler",
          "Temizlik Cihazları",
        ],
      },
      {
        name: "Otel ve Konaklama Mobilyaları",
        children: [
          "Otel Yatakları",
          "Otel Odası Mobilyaları",
          "Lobi Mobilyaları",
          "Restoran Masa ve Sandalyeleri",
          "Otel Dolapları",
          "Otel Tekstili",
          "Otel Oda Aksesuarları",
        ],
      },
    ],
  },
  {
    name: "Makine ve Ekipman",
    children: [
      {
        name: "Üretim Makineleri",
        children: [
          "CNC Makineleri",
          "Torna Tezgahları",
          "Freze Tezgahları",
          "Pres Makineleri",
          "Kesim Makineleri",
          "Büküm Makineleri",
          "Kaynak Makineleri",
          "Paketleme Makineleri",
          "Dolum Makineleri",
          "Etiketleme Makineleri",
          "Gıda Üretim Makineleri",
          "Tekstil Makineleri",
          "Plastik İşleme Makineleri",
        ],
      },
      {
        name: "Endüstriyel Ekipmanlar",
        children: [
          "Redüktörler",
          "Elektrik Motorları",
          "Konveyör Sistemleri",
          "Vibrasyon Ekipmanları",
          "Endüstriyel Fanlar",
          "Endüstriyel Isıtıcılar",
          "Vakum Sistemleri",
          "Kaldırma Ekipmanları",
          "Vinç ve Caraskallar",
          "Endüstriyel Tartım Sistemleri",
          "Üretim Hattı Ekipmanları",
        ],
      },
      {
        name: "Kompresör ve Pnömatik",
        children: [
          "Vidalı Kompresörler",
          "Pistonlu Kompresörler",
          "Hava Kurutucular",
          "Hava Tankları",
          "Pnömatik Silindirler",
          "Pnömatik Valfler",
          "Hava Hortumları",
          "Pnömatik Fittingsler",
          "FRL Üniteleri",
          "Pnömatik El Aletleri",
          "Kompresör Yedek Parçaları",
        ],
      },
      {
        name: "Pompa Sistemleri",
        children: [
          "Santrifüj Pompalar",
          "Dalgıç Pompalar",
          "Dişli Pompalar",
          "Dozaj Pompaları",
          "Kimyasal Pompalar",
          "Vakum Pompaları",
          "Endüstriyel Pompalar",
          "Pompa Motorları",
          "Pompa Kontrol Sistemleri",
          "Pompa Yedek Parçaları",
        ],
      },
      {
        name: "Yedek Parça ve Bakım",
        children: [
          "Makine Yedek Parçaları",
          "Kayış ve Kasnaklar",
          "Zincir ve Dişliler",
          "Kaplinler",
          "Keçe ve Contalar",
          "Lineer Hareket Sistemleri",
          "Makine Yağları",
          "Bakım Kimyasalları",
          "Bakım Ekipmanları",
          "Makine Koruma Ürünleri",
        ],
      },
    ],
  },
  {
    name: "Sanayi Sarf Malzemeleri",
    children: [
      {
        name: "Kesici Takımlar",
        children: [
          "Torna Uçları",
          "Freze Uçları",
          "Matkap Uçları",
          "Karbür Uçlar",
          "HSS Kesici Takımlar",
          "Kılavuzlar",
          "Paftalar",
          "Raybalar",
          "Delik Testereleri",
          "Kesici Takım Tutucuları",
        ],
      },
      {
        name: "Kaynak Sarfları",
        children: [
          "Kaynak Elektrotları",
          "MIG MAG Kaynak Telleri",
          "TIG Kaynak Telleri",
          "Özlü Kaynak Telleri",
          "Kaynak Nozulları",
          "Kaynak Torçları",
          "Kaynak Maskeleri",
          "Kaynak Eldivenleri",
          "Kaynak Spreyleri",
          "Kaynak Aksesuarları",
        ],
      },
      {
        name: "Taşlama ve Diskler",
        children: [
          "Kesme Diskleri",
          "Taşlama Diskleri",
          "Flap Diskler",
          "Zımpara Diskleri",
          "Elmas Diskler",
          "Tel Fırçalar",
          "Polisaj Diskleri",
          "Zımpara Bantları",
          "Aşındırıcı Ürünler",
        ],
      },
      {
        name: "Rulman ve Mekanik Sarf",
        children: [
          "Bilyalı Rulmanlar",
          "Makaralı Rulmanlar",
          "Konik Rulmanlar",
          "Yataklı Rulmanlar",
          "Lineer Rulmanlar",
          "Rulman Yatakları",
          "Keçeler",
          "Segmanlar",
          "Burçlar",
          "Kaplinler",
          "Zincirler",
          "Dişliler",
        ],
      },
      {
        name: "Bakım ve Yağlama Ürünleri",
        children: [
          "Endüstriyel Yağlar",
          "Gresler",
          "Kesme Yağları",
          "Hidrolik Yağlar",
          "Dişli Yağları",
          "Pas Sökücüler",
          "Yağlayıcı Spreyler",
          "Teknik Temizleyiciler",
          "Yağlama Ekipmanları",
          "Gres Tabancaları",
        ],
      },
    ],
  },
  {
    name: "Plastik ve Kimya",
    children: [
      {
        name: "Plastik Hammadde",
        children: [
          "Polietilen PE",
          "Polipropilen PP",
          "PVC",
          "PET",
          "Polistiren PS",
          "ABS",
          "Polikarbonat PC",
          "Poliamid PA",
          "EVA",
          "Termoplastik Elastomerler",
          "Mühendislik Plastikleri",
          "Geri Dönüştürülmüş Plastik Hammaddeler",
        ],
      },
      {
        name: "Granül",
        children: [
          "PE Granül",
          "PP Granül",
          "PVC Granül",
          "PET Granül",
          "ABS Granül",
          "PS Granül",
          "Masterbatch",
          "Renkli Granül",
          "Şeffaf Granül",
          "Geri Dönüşüm Granülü",
          "Dolgu Granülleri",
        ],
      },
      {
        name: "Endüstriyel Kimyasallar",
        children: [
          "Asitler",
          "Bazlar",
          "Alkoller",
          "Yüzey Aktif Maddeler",
          "Temizlik Kimyasalları",
          "Su Arıtma Kimyasalları",
          "Tekstil Kimyasalları",
          "Boya Kimyasalları",
          "Metal İşleme Kimyasalları",
          "Kauçuk Kimyasalları",
          "Gıda Sanayi Kimyasalları",
          "Kimyasal Katkı Maddeleri",
        ],
      },
      {
        name: "Solventler",
        children: [
          "Aseton",
          "İzopropil Alkol",
          "Etil Alkol",
          "Tinerler",
          "Toluen",
          "Ksilen",
          "Etil Asetat",
          "Butil Asetat",
          "Temizlik Solventleri",
          "Endüstriyel Çözücüler",
        ],
      },
      {
        name: "Yapıştırıcı ve Reçineler",
        children: [
          "Epoksi Reçineler",
          "Polyester Reçineler",
          "Poliüretan Reçineler",
          "Akrilik Reçineler",
          "Sıcak Tutkal",
          "Endüstriyel Yapıştırıcılar",
          "Kontakt Yapıştırıcılar",
          "Siyanoakrilat Yapıştırıcılar",
          "Laminasyon Yapıştırıcıları",
          "Ambalaj Yapıştırıcıları",
          "Sertleştiriciler",
          "Reçine Katkıları",
        ],
      },
    ],
  },
  {
    name: "Tarım ve Hayvancılık",
    children: [
      {
        name: "Sulama Sistemleri",
        children: [
          "Damla Sulama",
          "Yağmurlama Sistemleri",
          "Sulama Boruları",
          "Sulama Fittingsleri",
          "Filtre Sistemleri",
          "Sulama Vanaları",
          "Sulama Pompaları",
          "Sulama Otomasyonu",
          "Hortum ve Makaralar",
        ],
      },
      {
        name: "Tarım Ekipmanları",
        children: [
          "Toprak İşleme Ekipmanları",
          "Ekim ve Dikim Ekipmanları",
          "Hasat Ekipmanları",
          "İlaçlama Ekipmanları",
          "Gübreleme Ekipmanları",
          "Budama Ekipmanları",
          "Tarım El Aletleri",
          "Motorlu Bahçe Ekipmanları",
          "Tarım Makinesi Yedek Parçaları",
        ],
      },
      {
        name: "Yem ve Besleme",
        children: [
          "Büyükbaş Yemleri",
          "Küçükbaş Yemleri",
          "Kanatlı Yemleri",
          "Yem Katkıları",
          "Mineral ve Premiksler",
          "Yalama Taşları",
          "Yemlikler",
          "Suluklar",
          "Yem Depolama Ekipmanları",
        ],
      },
      {
        name: "Seracılık Malzemeleri",
        children: [
          "Sera Örtüleri",
          "Gölgeleme Fileleri",
          "Sera Klipsleri",
          "Sera İpleri",
          "Fide ve Yetiştirme Kapları",
          "Sera Sulama Sistemleri",
          "Sera Isıtma Ekipmanları",
          "Sera Havalandırma Ekipmanları",
          "Sera Yapı Aksesuarları",
        ],
      },
      {
        name: "Hayvancılık Ekipmanları",
        children: [
          "Sağım Ekipmanları",
          "Hayvan Sulukları",
          "Hayvan Yemlikleri",
          "Ahır Ekipmanları",
          "Çiftlik Havalandırma Sistemleri",
          "Hayvan Tartım Sistemleri",
          "Hayvan Taşıma Ekipmanları",
          "Çiftlik Temizlik Ekipmanları",
          "Hayvancılık Sarf Malzemeleri",
        ],
      },
    ],
  },
  {
    name: "Lojistik ve Depolama",
    children: [
      {
        name: "Palet",
        children: [
          "Ahşap Paletler",
          "Plastik Paletler",
          "Metal Paletler",
          "Euro Paletler",
          "Palet Kasaları",
          "Palet Aksesuarları",
        ],
      },
      {
        name: "Raf Sistemleri",
        children: [
          "Palet Rafları",
          "Depo Rafları",
          "Ağır Yük Rafları",
          "Hafif Yük Rafları",
          "Arşiv Rafları",
          "Raf Aksesuarları",
        ],
      },
      {
        name: "Depo Ekipmanları",
        children: [
          "Transpaletler",
          "İstif Makineleri",
          "Forklift Ekipmanları",
          "Yük Taşıma Arabaları",
          "Platform Arabaları",
          "Depo Güvenlik Ekipmanları",
        ],
      },
      {
        name: "Ambalaj ve Sevkiyat",
        children: [
          "Sevkiyat Kolileri",
          "Palet Streçleri",
          "Çemberleme Ürünleri",
          "Koruyucu Ambalajlar",
          "Sevkiyat Etiketleri",
          "Kargo ve Sevkiyat Sarfları",
        ],
      },
      {
        name: "Taşıma Hizmetleri",
        children: [
          "Karayolu Taşımacılığı",
          "Denizyolu Taşımacılığı",
          "Havayolu Taşımacılığı",
          "Uluslararası Taşımacılık",
          "Parsiyel Taşımacılık",
          "Depolama ve Dağıtım Hizmetleri",
        ],
      },
    ],
  },
  {
    name: "Elektronik, Bilişim & Teknoloji",
    children: [
      {
        name: "Bilgisayar ve Çevre Birimleri",
        children: [
          "Masaüstü Bilgisayarlar",
          "Dizüstü Bilgisayarlar",
          "Monitörler",
          "Klavye ve Mouse",
          "Web Kameraları",
          "Kulaklık ve Mikrofonlar",
          "Bilgisayar Kasaları",
          "Anakartlar",
          "İşlemciler",
          "RAM Bellekler",
          "Ekran Kartları",
          "Bilgisayar Güç Kaynakları",
          "Bilgisayar Aksesuarları",
        ],
      },
      {
        name: "Ağ ve Network",
        children: [
          "Modem ve Router",
          "Switchler",
          "Access Point",
          "Network Kabloları",
          "Fiber Optik Ürünler",
          "Patch Paneller",
          "Network Kabinleri",
          "Network Kartları",
          "PoE Ürünleri",
          "Network Konnektörleri",
          "Network Test Cihazları",
        ],
      },
      {
        name: "Elektronik Bileşenler",
        children: [
          "Dirençler",
          "Kondansatörler",
          "Diyotlar",
          "Transistörler",
          "Entegre Devreler",
          "Röleler",
          "Sensörler",
          "Konnektörler",
          "Devre Kartları",
          "PCB Malzemeleri",
          "Elektronik Modüller",
          "Elektronik Sarf Malzemeleri",
        ],
      },
      {
        name: "Yazıcı ve Ofis Teknolojileri",
        children: [
          "Lazer Yazıcılar",
          "Mürekkep Püskürtmeli Yazıcılar",
          "Çok Fonksiyonlu Yazıcılar",
          "Tarayıcılar",
          "Fotokopi Makineleri",
          "Projeksiyon Cihazları",
          "Tonerler",
          "Kartuşlar",
          "Yazıcı Şeritleri",
          "Yazıcı Yedek Parçaları",
          "Ofis Teknolojisi Aksesuarları",
        ],
      },
      {
        name: "Teknolojik Ekipmanlar",
        children: [
          "Tabletler",
          "Akıllı Ekranlar",
          "Dokunmatik Ekranlar",
          "Dijital Bilgilendirme Sistemleri",
          "Toplantı Sistemleri",
          "Video Konferans Sistemleri",
          "Sunum Sistemleri",
          "Endüstriyel Tabletler",
          "Taşınabilir Teknoloji Ekipmanları",
        ],
      },
      {
        name: "Telefon ve Mobil Aksesuarlar",
        children: [
          "Cep Telefonları",
          "Kurumsal Telefonlar",
          "Telefon Kılıfları",
          "Ekran Koruyucular",
          "Şarj Cihazları",
          "Şarj Kabloları",
          "Powerbank",
          "Araç Telefon Aksesuarları",
          "Mobil Cihaz Aksesuarları",
        ],
      },
      {
        name: "Veri Depolama",
        children: [
          "SSD Diskler",
          "Hard Diskler",
          "Harici Diskler",
          "USB Bellekler",
          "Hafıza Kartları",
          "NAS Sistemleri",
          "Sunucu Diskleri",
          "Veri Depolama Aksesuarları",
        ],
      },
      {
        name: "Güç Kaynakları ve UPS",
        children: [
          "Kesintisiz Güç Kaynakları",
          "Online UPS",
          "Line Interactive UPS",
          "Adaptörler",
          "AC DC Güç Kaynakları",
          "Endüstriyel Güç Kaynakları",
          "Priz ve Akım Korumalı Ürünler",
          "UPS Aküleri",
        ],
      },
      {
        name: "POS ve Barkod Sistemleri",
        children: [
          "Barkod Okuyucular",
          "Barkod Yazıcılar",
          "Termal Yazıcılar",
          "POS Terminalleri",
          "Dokunmatik POS Sistemleri",
          "El Terminalleri",
          "Etiket Yazıcılar",
          "Para Çekmeceleri",
          "Barkod Etiketleri",
          "Termal Rulolar",
        ],
      },
      {
        name: "Görüntü ve Ses Sistemleri",
        children: [
          "Televizyon ve Ekranlar",
          "Profesyonel Monitörler",
          "Hoparlörler",
          "Amplifikatörler",
          "Mikrofonlar",
          "Ses Sistemleri",
          "Projeksiyon Perdeleri",
          "HDMI ve Görüntü Kabloları",
          "Ses Kabloları ve Konnektörleri",
        ],
      },
      {
        name: "Endüstriyel Elektronik",
        children: [
          "PLC Sistemleri",
          "HMI Paneller",
          "Endüstriyel Bilgisayarlar",
          "Endüstriyel Sensörler",
          "Encoderler",
          "Kontrol Modülleri",
          "Sinyal Dönüştürücüler",
          "Endüstriyel Haberleşme Ürünleri",
          "Otomasyon Aksesuarları",
        ],
      },
    ],
  },
  {
    name: "İklimlendirme ve HVAC",
    children: [
      {
        name: "Klima Sistemleri",
        children: [
          "Split Klimalar",
          "Salon Tipi Klimalar",
          "Kaset Tipi Klimalar",
          "VRF Sistemleri",
          "Endüstriyel Klimalar",
          "Klima Aksesuarları",
        ],
      },
      {
        name: "Havalandırma",
        children: [
          "Havalandırma Fanları",
          "Aspiratörler",
          "Hava Perdeleri",
          "Isı Geri Kazanım Cihazları",
          "Menfez ve Difüzörler",
          "Havalandırma Aksesuarları",
        ],
      },
      {
        name: "Soğutma Sistemleri",
        children: [
          "Soğuk Oda Sistemleri",
          "Chiller Sistemleri",
          "Soğutma Grupları",
          "Kondenserler",
          "Evaporatörler",
          "Soğutma Ekipmanları",
        ],
      },
      {
        name: "HVAC Sarf Malzemeleri",
        children: [
          "Soğutucu Gazlar",
          "Bakır Borular",
          "Boru İzolasyonları",
          "Drenaj Hortumları",
          "Montaj Konsolları",
          "HVAC Bakım Ürünleri",
        ],
      },
      {
        name: "Filtre ve Kanal Sistemleri",
        children: [
          "Hava Filtreleri",
          "HEPA Filtreler",
          "Havalandırma Kanalları",
          "Esnek Hava Kanalları",
          "Kanal Bağlantı Elemanları",
          "Kanal İzolasyonları",
        ],
      },
    ],
  },
  {
    name: "Su ve Tesisat",
    children: [
      {
        name: "Boru ve Fittings",
        children: [
          "PPRC Boru ve Ek Parçaları",
          "PVC Boru ve Ek Parçaları",
          "PE Boru ve Ek Parçaları",
          "Koruge Boru ve Ek Parçaları",
          "Çelik Boru ve Ek Parçaları",
          "Bakır Boru ve Ek Parçaları",
          "Drenaj Boruları",
          "Atık Su Boruları",
          "Boru Kelepçeleri",
        ],
      },
      {
        name: "Vana ve Armatür",
        children: [
          "Küresel Vanalar",
          "Kelebek Vanalar",
          "Sürgülü Vanalar",
          "Çekvalfler",
          "Basınç Düşürücüler",
          "Pislik Tutucular",
          "Musluklar",
          "Bataryalar",
          "Endüstriyel Vanalar",
          "Vana Aksesuarları",
        ],
      },
      {
        name: "Sıhhi Tesisat",
        children: [
          "Lavabolar",
          "Klozet ve Rezervuarlar",
          "Duş Sistemleri",
          "Evye ve Mutfak Armatürleri",
          "Sifonlar",
          "Gider Sistemleri",
          "Yer Süzgeçleri",
          "Taharet Muslukları",
          "Banyo Aksesuarları",
          "Tesisat Bağlantı Hortumları",
        ],
      },
      {
        name: "Pompa ve Hidrofor",
        children: [
          "Hidroforlar",
          "Dalgıç Pompalar",
          "Santrifüj Pompalar",
          "Sirkülasyon Pompaları",
          "Atık Su Pompaları",
          "Drenaj Pompaları",
          "Pompa Kontrol Sistemleri",
          "Genleşme Tankları",
          "Pompa Yedek Parçaları",
        ],
      },
      {
        name: "Tesisat Sarf Malzemeleri",
        children: [
          "Teflon Bantlar",
          "Keten ve Sızdırmazlık Ürünleri",
          "Conta ve O-Ringler",
          "Boru İzolasyonları",
          "Tesisat Kelepçeleri",
          "Bağlantı Hortumları",
          "Tesisat Yapıştırıcıları",
          "Montaj Sarf Malzemeleri",
          "Tesisat El Aletleri",
        ],
      },
    ],
  },
  {
    name: "Güvenlik ve Yangın Sistemleri",
    children: [
      {
        name: "Kamera Sistemleri",
        children: [
          "IP Kameralar",
          "Analog Kameralar",
          "Dome Kameralar",
          "Bullet Kameralar",
          "PTZ Kameralar",
          "Kayıt Cihazları",
          "Kamera Lensleri",
          "Kamera Güç Kaynakları",
          "Kamera Montaj Aksesuarları",
          "Video Gözetim Depolama Ürünleri",
        ],
      },
      {
        name: "Alarm Sistemleri",
        children: [
          "Hırsız Alarm Sistemleri",
          "Alarm Panelleri",
          "Hareket Sensörleri",
          "Manyetik Kontaklar",
          "Sirenler",
          "Gaz Dedektörleri",
          "Su Baskını Dedektörleri",
          "Alarm Kumandaları",
          "Alarm Haberleşme Modülleri",
        ],
      },
      {
        name: "Yangın Söndürme",
        children: [
          "Yangın Söndürme Tüpleri",
          "Yangın Dolapları",
          "Yangın Hortumları",
          "Yangın Vanaları",
          "Sprinkler Sistemleri",
          "Yangın Algılama Sistemleri",
          "Duman Dedektörleri",
          "Isı Dedektörleri",
          "Yangın Alarm Butonları",
          "Acil Çıkış Ürünleri",
        ],
      },
      {
        name: "Geçiş Kontrol Sistemleri",
        children: [
          "Kartlı Geçiş Sistemleri",
          "Parmak İzi Sistemleri",
          "Yüz Tanıma Sistemleri",
          "Turnikeler",
          "Bariyer Sistemleri",
          "Elektrikli Kilitler",
          "Kart ve Anahtarlıklar",
          "Geçiş Kontrol Panelleri",
          "Personel Takip Sistemleri",
        ],
      },
      {
        name: "Güvenlik Ekipmanları",
        children: [
          "Güvenlik Aynaları",
          "İkaz Levhaları",
          "Güvenlik Bariyerleri",
          "Trafik Konileri",
          "Şerit ve Zincir Bariyerler",
          "Acil Durum Ekipmanları",
          "Güvenlik Dolapları",
          "Anahtar Saklama Sistemleri",
        ],
      },
    ],
  },
  {
    name: "Reklam ve Promosyon",
    children: [
      {
        name: "Promosyon Ürünleri",
        children: [
          "Promosyon Kalemler",
          "Promosyon Defterler",
          "Promosyon Ajandalar",
          "Promosyon Kupalar",
          "Promosyon Çantalar",
          "Promosyon Tekstil Ürünleri",
          "Promosyon USB Bellekler",
          "Promosyon Powerbank",
          "Promosyon Anahtarlıklar",
          "Promosyon Şemsiyeler",
          "Promosyon Matara ve Termoslar",
        ],
      },
      {
        name: "Tabela ve Baskı",
        children: [
          "Işıklı Tabelalar",
          "Işıksız Tabelalar",
          "Yönlendirme Tabelaları",
          "Pleksi Tabelalar",
          "Metal Tabelalar",
          "Kapı Tabelaları",
          "Folyo Kesim",
          "Araç Giydirme",
          "Vitrin Uygulamaları",
          "Tabela Malzemeleri",
        ],
      },
      {
        name: "Kurumsal Hediyeler",
        children: [
          "Kurumsal Hediye Setleri",
          "Kalem Setleri",
          "Ajanda Setleri",
          "Masaüstü Hediyelikler",
          "Termos ve Matara Setleri",
          "Teknolojik Hediyeler",
          "Özel Tasarım Hediyeler",
          "Personel Hediye Setleri",
        ],
      },
      {
        name: "Dijital Baskı",
        children: [
          "Branda Baskı",
          "Folyo Baskı",
          "Poster Baskı",
          "Afiş Baskı",
          "Kanvast Baskı",
          "UV Baskı",
          "Tekstil Baskı",
          "Süblimasyon Baskı",
          "Sticker Baskı",
          "Büyük Format Baskı",
        ],
      },
      {
        name: "Tanıtım Malzemeleri",
        children: [
          "Roll Up",
          "Örümcek Stand",
          "Tanıtım Standları",
          "Fuar Stand Ürünleri",
          "Broşürlükler",
          "Bayraklar",
          "Flamalar",
          "Masa Bayrakları",
          "Yaka Kartları",
          "Fuar ve Etkinlik Malzemeleri",
        ],
      },
    ],
  },
  {
    name: "Kırtasiye ve Matbaa",
    children: [
      {
        name: "Ofis Kırtasiyesi",
        children: [
          "Tükenmez Kalemler",
          "Jel Kalemler",
          "Marker ve Tahta Kalemleri",
          "Fosforlu Kalemler",
          "Zımba ve Zımba Telleri",
          "Delgeçler",
          "Dosya ve Klasörler",
          "Masaüstü Düzenleyiciler",
          "Bant ve Yapıştırıcılar",
          "Makas ve Kesiciler",
          "Ajanda ve Not Defterleri",
          "Ofis Sarf Malzemeleri",
        ],
      },
      {
        name: "Kağıt Ürünleri",
        children: [
          "Fotokopi Kağıtları",
          "Bristol Kağıt",
          "Kuşe Kağıt",
          "Kraft Kağıt",
          "Renkli Kağıtlar",
          "Etiket Kağıtları",
          "Plotter Kağıtları",
          "Termal Kağıtlar",
          "Kartonlar",
          "Zarf ve Postalama Ürünleri",
        ],
      },
      {
        name: "Matbaa Sarf Malzemeleri",
        children: [
          "Matbaa Mürekkepleri",
          "Ofset Baskı Malzemeleri",
          "Serigrafi Malzemeleri",
          "Baskı Kalıpları",
          "Laminasyon Filmleri",
          "Selefon Malzemeleri",
          "Ciltleme Malzemeleri",
          "Kesim Malzemeleri",
          "Matbaa Kimyasalları",
          "Baskı Temizlik Ürünleri",
        ],
      },
      {
        name: "Baskı Hizmetleri",
        children: [
          "Kartvizit Baskı",
          "Broşür Baskı",
          "Katalog Baskı",
          "El İlanı Baskı",
          "Davetiye Baskı",
          "Dosya Baskı",
          "Kurumsal Evrak Baskı",
          "Kitap ve Dergi Baskı",
          "Özel Ölçü Baskı",
        ],
      },
      {
        name: "Etiket ve Ambalaj Baskı",
        children: [
          "Rulo Etiket",
          "Kuşe Etiket",
          "Termal Etiket",
          "Şeffaf Etiket",
          "Kraft Etiket",
          "Barkod Etiketleri",
          "Tekstil Etiketleri",
          "Kutu Baskı",
          "Poşet Baskı",
          "Ambalaj Üzeri Baskı",
          "Özel Kesim Etiketler",
        ],
      },
    ],
  },
  {
    name: "Enerji ve Güneş Sistemleri",
    children: [
      {
        name: "Güneş Panelleri",
        children: [
          "Monokristal Güneş Panelleri",
          "Polikristal Güneş Panelleri",
          "Bifacial Güneş Panelleri",
          "Esnek Güneş Panelleri",
          "Endüstriyel Güneş Panelleri",
          "Off-Grid Güneş Panelleri",
          "Solar Panel Montaj Sistemleri",
        ],
      },
      {
        name: "İnverter",
        children: [
          "On-Grid İnverterler",
          "Off-Grid İnverterler",
          "Hibrit İnverterler",
          "Solar Pompa İnverterleri",
          "Mikro İnverterler",
          "Endüstriyel İnverterler",
          "İnverter Aksesuarları",
        ],
      },
      {
        name: "Enerji Depolama",
        children: [
          "Lityum Aküler",
          "Jel Aküler",
          "AGM Aküler",
          "Solar Aküler",
          "Enerji Depolama Sistemleri",
          "Batarya Modülleri",
          "Batarya Yönetim Sistemleri",
          "Akü Kabinleri",
        ],
      },
      {
        name: "Solar Kablo ve Aksesuar",
        children: [
          "Solar Kablolar",
          "MC4 Konnektörler",
          "Solar Sigortalar",
          "DC Şalterler",
          "Solar Konnektörler",
          "Kablo Taşıma Sistemleri",
          "Topraklama Ekipmanları",
          "Panel Bağlantı Aksesuarları",
        ],
      },
      {
        name: "Enerji Sistemleri Ekipmanları",
        children: [
          "Solar Şarj Kontrol Cihazları",
          "Enerji Sayaçları",
          "Enerji İzleme Sistemleri",
          "DC Panolar",
          "AC Panolar",
          "Kompanzasyon Sistemleri",
          "Jeneratörler",
          "Transfer Şalterleri",
          "Enerji Kalitesi Cihazları",
          "GES Montaj Ekipmanları",
        ],
      },
    ],
  },
  {
    name: "Maden ve Endüstriyel Üretim",
    children: [
      {
        name: "Madencilik Ekipmanları",
        children: [
          "Kırma ve Eleme Ekipmanları",
          "Sondaj Ekipmanları",
          "Kaya Delme Ekipmanları",
          "Maden Pompaları",
          "Maden Havalandırma Ekipmanları",
          "Madencilik Yedek Parçaları",
        ],
      },
      {
        name: "Ağır Sanayi Ekipmanları",
        children: [
          "Vinç Sistemleri",
          "Kaldırma Ekipmanları",
          "Hidrolik Sistemler",
          "Endüstriyel Redüktörler",
          "Ağır Hizmet Motorları",
          "Ağır Sanayi Yedek Parçaları",
        ],
      },
      {
        name: "Saha Sarf Malzemeleri",
        children: [
          "Sondaj Sarf Malzemeleri",
          "Aşındırıcı Ürünler",
          "Endüstriyel Hortumlar",
          "Saha Güvenlik Ürünleri",
          "Teknik Yağlayıcılar",
          "Bakım Sarf Malzemeleri",
        ],
      },
      {
        name: "Konveyör ve Taşıma Sistemleri",
        children: [
          "Konveyör Bantları",
          "Konveyör Ruloları",
          "Bant Tamburları",
          "Zincirli Konveyörler",
          "Helezon Konveyörler",
          "Konveyör Aksesuarları",
        ],
      },
      {
        name: "Endüstriyel Üretim Ekipmanları",
        children: [
          "Üretim Hattı Ekipmanları",
          "Endüstriyel Karıştırıcılar",
          "Dozajlama Sistemleri",
          "Eleme Sistemleri",
          "Endüstriyel Kurutucular",
          "Proses Ekipmanları",
        ],
      },
    ],
  },];

async function ensureCategory(name: string, parentId: string | null = null) {
  const existing = await prisma.category.findFirst({
    where: {
      name,
      parentId,
    },
  });

  if (existing) {
    return existing;
  }

  return prisma.category.create({
    data: {
      name,
      parentId,
    },
  });
}

async function syncCategory(
  category: CategorySeed,
  parentId: string | null = null,
) {
  const current = await ensureCategory(category.name, parentId);

  for (const child of category.children ?? []) {
    if (typeof child === "string") {
      await ensureCategory(child, current.id);
    } else {
      await syncCategory(child, current.id);
    }
  }
}

async function renameLegacyCategories() {
  const oldElectronics = await prisma.category.findFirst({
    where: {
      name: "Elektronik ve Teknoloji",
      parentId: null,
    },
  });

  const newElectronics = await prisma.category.findFirst({
    where: {
      name: "Elektronik, Bilişim & Teknoloji",
      parentId: null,
    },
  });

  if (oldElectronics && !newElectronics) {
    await prisma.category.update({
      where: { id: oldElectronics.id },
      data: { name: "Elektronik, Bilişim & Teknoloji" },
    });

    console.log(
      "✅ Elektronik ve Teknoloji → Elektronik, Bilişim & Teknoloji",
    );
  }
}

async function main() {
  await renameLegacyCategories();

  for (const category of categories) {
    await syncCategory(category);
  }

  console.log("✅ Categories synchronized successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
